// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/snippet_service.proto

package phil0522_taskd

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShellSnippetRequest struct {
	CurrentDirectory string `protobuf:"bytes,1,opt,name=current_directory,json=currentDirectory,proto3" json:"current_directory,omitempty"`
	// The current input.
	CmdPrefix            string   `protobuf:"bytes,2,opt,name=cmd_prefix,json=cmdPrefix,proto3" json:"cmd_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShellSnippetRequest) Reset()         { *m = ShellSnippetRequest{} }
func (m *ShellSnippetRequest) String() string { return proto.CompactTextString(m) }
func (*ShellSnippetRequest) ProtoMessage()    {}
func (*ShellSnippetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd244997a2724ff9, []int{0}
}

func (m *ShellSnippetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShellSnippetRequest.Unmarshal(m, b)
}
func (m *ShellSnippetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShellSnippetRequest.Marshal(b, m, deterministic)
}
func (m *ShellSnippetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShellSnippetRequest.Merge(m, src)
}
func (m *ShellSnippetRequest) XXX_Size() int {
	return xxx_messageInfo_ShellSnippetRequest.Size(m)
}
func (m *ShellSnippetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShellSnippetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShellSnippetRequest proto.InternalMessageInfo

func (m *ShellSnippetRequest) GetCurrentDirectory() string {
	if m != nil {
		return m.CurrentDirectory
	}
	return ""
}

func (m *ShellSnippetRequest) GetCmdPrefix() string {
	if m != nil {
		return m.CmdPrefix
	}
	return ""
}

type ShellSnippetResponse struct {
	ShellSnippet         []*ShellSnippet `protobuf:"bytes,1,rep,name=shell_snippet,json=shellSnippet,proto3" json:"shell_snippet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ShellSnippetResponse) Reset()         { *m = ShellSnippetResponse{} }
func (m *ShellSnippetResponse) String() string { return proto.CompactTextString(m) }
func (*ShellSnippetResponse) ProtoMessage()    {}
func (*ShellSnippetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd244997a2724ff9, []int{1}
}

func (m *ShellSnippetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShellSnippetResponse.Unmarshal(m, b)
}
func (m *ShellSnippetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShellSnippetResponse.Marshal(b, m, deterministic)
}
func (m *ShellSnippetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShellSnippetResponse.Merge(m, src)
}
func (m *ShellSnippetResponse) XXX_Size() int {
	return xxx_messageInfo_ShellSnippetResponse.Size(m)
}
func (m *ShellSnippetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShellSnippetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShellSnippetResponse proto.InternalMessageInfo

func (m *ShellSnippetResponse) GetShellSnippet() []*ShellSnippet {
	if m != nil {
		return m.ShellSnippet
	}
	return nil
}

type ShellSnippet struct {
	SnippetName          string   `protobuf:"bytes,1,opt,name=snippet_name,json=snippetName,proto3" json:"snippet_name,omitempty"`
	SnippetDescription   string   `protobuf:"bytes,2,opt,name=snippet_description,json=snippetDescription,proto3" json:"snippet_description,omitempty"`
	SnippetCommand       string   `protobuf:"bytes,3,opt,name=snippet_command,json=snippetCommand,proto3" json:"snippet_command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShellSnippet) Reset()         { *m = ShellSnippet{} }
func (m *ShellSnippet) String() string { return proto.CompactTextString(m) }
func (*ShellSnippet) ProtoMessage()    {}
func (*ShellSnippet) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd244997a2724ff9, []int{2}
}

func (m *ShellSnippet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShellSnippet.Unmarshal(m, b)
}
func (m *ShellSnippet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShellSnippet.Marshal(b, m, deterministic)
}
func (m *ShellSnippet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShellSnippet.Merge(m, src)
}
func (m *ShellSnippet) XXX_Size() int {
	return xxx_messageInfo_ShellSnippet.Size(m)
}
func (m *ShellSnippet) XXX_DiscardUnknown() {
	xxx_messageInfo_ShellSnippet.DiscardUnknown(m)
}

var xxx_messageInfo_ShellSnippet proto.InternalMessageInfo

func (m *ShellSnippet) GetSnippetName() string {
	if m != nil {
		return m.SnippetName
	}
	return ""
}

func (m *ShellSnippet) GetSnippetDescription() string {
	if m != nil {
		return m.SnippetDescription
	}
	return ""
}

func (m *ShellSnippet) GetSnippetCommand() string {
	if m != nil {
		return m.SnippetCommand
	}
	return ""
}

func init() {
	proto.RegisterType((*ShellSnippetRequest)(nil), "phil0522.taskd.ShellSnippetRequest")
	proto.RegisterType((*ShellSnippetResponse)(nil), "phil0522.taskd.ShellSnippetResponse")
	proto.RegisterType((*ShellSnippet)(nil), "phil0522.taskd.ShellSnippet")
}

func init() {
	proto.RegisterFile("proto/snippet_service.proto", fileDescriptor_dd244997a2724ff9)
}

var fileDescriptor_dd244997a2724ff9 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0x86, 0xad, 0x03, 0x61, 0x67, 0xb5, 0x6a, 0xe6, 0x45, 0xf1, 0x03, 0x66, 0x15, 0x1c, 0x08,
	0x9d, 0x54, 0xfc, 0x01, 0xe2, 0xae, 0x45, 0xd6, 0x2b, 0xaf, 0x4a, 0x4c, 0x8e, 0x34, 0xd8, 0x7c,
	0x98, 0x64, 0xa2, 0xbf, 0xc1, 0x3f, 0x2d, 0xb6, 0x29, 0xae, 0x37, 0xbb, 0xec, 0xf3, 0xbe, 0xa1,
	0xcf, 0x39, 0x07, 0x4e, 0x8d, 0xd5, 0x5e, 0x2f, 0x9c, 0x12, 0xc6, 0xa0, 0xaf, 0x1c, 0xda, 0x4f,
	0xc1, 0x30, 0x6f, 0x29, 0x49, 0x4c, 0x2d, 0x9a, 0xdb, 0xfb, 0xa2, 0xc8, 0x3d, 0x75, 0xef, 0x3c,
	0xa3, 0x30, 0x2d, 0x6b, 0x6c, 0x9a, 0xb2, 0x6b, 0xaf, 0xf0, 0x63, 0x8d, 0xce, 0x93, 0x1b, 0x38,
	0x62, 0x6b, 0x6b, 0x51, 0xf9, 0x8a, 0x0b, 0x8b, 0xcc, 0x6b, 0xfb, 0x9d, 0x46, 0xb3, 0x68, 0x3e,
	0x5e, 0x1d, 0x86, 0x60, 0xd9, 0x73, 0x72, 0x0e, 0xc0, 0x24, 0xaf, 0x8c, 0xc5, 0x37, 0xf1, 0x95,
	0xee, 0xb6, 0xad, 0x31, 0x93, 0xfc, 0xb9, 0x05, 0xd9, 0x0b, 0x1c, 0x0f, 0x7f, 0xe1, 0x8c, 0x56,
	0x0e, 0xc9, 0x03, 0xec, 0xbb, 0x3f, 0x5e, 0x05, 0xd3, 0x34, 0x9a, 0x8d, 0xe6, 0x93, 0xe2, 0x2c,
	0x1f, 0x2a, 0xe6, 0x83, 0xc7, 0xb1, 0xdb, 0xf8, 0xca, 0x7e, 0x22, 0x88, 0x37, 0x63, 0x72, 0x01,
	0x71, 0x3f, 0xb7, 0xa2, 0x12, 0x83, 0xf2, 0x24, 0xb0, 0x27, 0x2a, 0x91, 0x2c, 0x60, 0xda, 0x57,
	0x38, 0x3a, 0x66, 0x85, 0xf1, 0x42, 0xab, 0xa0, 0x4d, 0x42, 0xb4, 0xfc, 0x4f, 0xc8, 0x35, 0x1c,
	0xf4, 0x0f, 0x98, 0x96, 0x92, 0x2a, 0x9e, 0x8e, 0xda, 0x72, 0x12, 0xf0, 0x63, 0x47, 0x0b, 0x07,
	0x49, 0xf0, 0x28, 0xbb, 0x9d, 0x13, 0x0a, 0xa4, 0x44, 0x6a, 0x59, 0x3d, 0x90, 0xbc, 0xdc, 0x3a,
	0x61, 0x77, 0x81, 0x93, 0xab, 0xed, 0xa5, 0x6e, 0x87, 0xd9, 0xce, 0xeb, 0x5e, 0x7b, 0xd7, 0xbb,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x59, 0xf5, 0x6f, 0xf6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SnippetServiceClient is the client API for SnippetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnippetServiceClient interface {
	SearchShellSnippet(ctx context.Context, in *ShellSnippetRequest, opts ...grpc.CallOption) (*ShellSnippetResponse, error)
}

type snippetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnippetServiceClient(cc grpc.ClientConnInterface) SnippetServiceClient {
	return &snippetServiceClient{cc}
}

func (c *snippetServiceClient) SearchShellSnippet(ctx context.Context, in *ShellSnippetRequest, opts ...grpc.CallOption) (*ShellSnippetResponse, error) {
	out := new(ShellSnippetResponse)
	err := c.cc.Invoke(ctx, "/phil0522.taskd.SnippetService/SearchShellSnippet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnippetServiceServer is the server API for SnippetService service.
type SnippetServiceServer interface {
	SearchShellSnippet(context.Context, *ShellSnippetRequest) (*ShellSnippetResponse, error)
}

// UnimplementedSnippetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSnippetServiceServer struct {
}

func (*UnimplementedSnippetServiceServer) SearchShellSnippet(ctx context.Context, req *ShellSnippetRequest) (*ShellSnippetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchShellSnippet not implemented")
}

func RegisterSnippetServiceServer(s *grpc.Server, srv SnippetServiceServer) {
	s.RegisterService(&_SnippetService_serviceDesc, srv)
}

func _SnippetService_SearchShellSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShellSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetServiceServer).SearchShellSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phil0522.taskd.SnippetService/SearchShellSnippet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetServiceServer).SearchShellSnippet(ctx, req.(*ShellSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SnippetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phil0522.taskd.SnippetService",
	HandlerType: (*SnippetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchShellSnippet",
			Handler:    _SnippetService_SearchShellSnippet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/snippet_service.proto",
}
